apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-pvc
        - name: dnsmasq-config
          configMap:
            name: dnsmasq-config
        - name: pihole-config
          configMap:
            name: pihole-config
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 80
            - containerPort: 53
              protocol: UDP
          env:
            - name: ServerIP
              value: "<ip_address>" # Replace with your Raspberry Pi's IP address
            - name: WEBPASSWORD
              value: "<password>"  # Replace with your desired Pi-hole admin password
          volumeMounts:
            - mountPath: "/etc/pihole"
              name: pihole-data
            - mountPath: "/etc/dnsmasq.d"
              name: dnsmasq-config
            - mountPath: "/etc/pihole-config"
              name: pihole-config
      dnsPolicy: Default

